package store

// Domain queries are generated by sqlc from schema/query/*.sql against
// schema/schema.sql into gen/query/. Run "go generate ./pkg/cmdman/store" (or
// "go tool sqlc generate" from this directory) after changing either.
//go:generate go tool sqlc generate
